= Echo Framework
:toc:

Simple event-based framework for developing high concurrent applications wth event-based domain model.

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-core</artifactId>
    <version>0.5.0</version>
</dependency>
----

You may want to use this library in Spring application.
If true you can add special dependency which will provide you annotation-based approach to register events and their handlers onto bus:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-spring</artifactId>
    <version>0.5.0</version>
</dependency>
----

For Quarkus integration you need the following:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-quarkus</artifactId>
    <version>0.5.0</version>
</dependency>
----

For more information of such integrations read <<Usage with Spring>> or <<Usage with Quarkus>>.

== Usage

== Usage with Spring

Requires JVM option `echo.packages.to.scan` (comma separated list of packages) to discover event locations. Example:
[source,bash]
----
java -Decho.packages.to.scan=com.example.one,com.example.two ...
----

Package `echo-spring` provides three annotations:

* `@Handler` -- marks that this class contains handlers of a number of events;
* `@Handles` -- marks that this method is handler of some event;
* `@HandlesExceptionsOf` -- marks that this method must be triggered if there will be any exception in `@Handles`-method. Scope of such handles consists of methods in `@Handler`-class.

Also, this package provides Spring-configuration class called `EchoSpringConfiguration` which must be included to Spring application context, for example, in the following way:

[source,java]
----
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(
            new Class[] {Application.class, EchoSpringConfiguration.class},
            args
        );
    }
}
----

After that you will have bean of type `Bus` in the application context with automatically registered event handlers based on mentioned annotations.

There a number of ways how to declare handlers for auto registration.

=== `SelfHandler` interface

All events which implement interface `SelfHandler` will be auto registered.

[source,java]
----
public class SomeEvent
    extends Event
    implements SelfHandler {
    // implementation
}
----

=== Static methods

[source,java]
----
@Handler
public class SomeHandler {

    @Handles
    public static void handler(SomeEvent e, Bus bus) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public static void onException(SomeEvent e, Throwable ex, Bus bus) {}
}
----

=== Bean

[source,java]
----
@Handler
public class SomeHandler {

    private final Bus bus;

    public SomeHandler(@Lazy Bus bus) {
        this.bus = bus;
    }

    @Handles
    public void handler(SomeEvent e) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public void onException(SomeEvent e, Throwable ex) {}
}
----

It is important to lazy wire `Bus` dependency.

== Usage with Quarkus

Requires JVM option `echo.packages.to.scan` (comma separated list of packages) to discover event locations. Example:
[source,bash]
----
java -Decho.packages.to.scan=com.example.one,com.example.two ...
----

Package `echo-quarkus` provides three annotations:

* `@Handler` -- marks that this class contains handlers of a number of events;
* `@Handles` -- marks that this method is handler of some event;
* `@HandlesExceptionsOf` -- marks that this method must be triggered if there will be any exception in `@Handles`-method. Scope of such handles consists of methods in `@Handler`-class.

Also, this package provides Spring-configuration class called `EchoQuarkusConfiguration` which provides singleton instance of `Bus` to CDI. It automatically registers event handlers onto bus.

There a number of ways how to declare handlers for auto registration.

=== `SelfHandler` interface

All events which implement interface `SelfHandler` will be auto registered.

[source,java]
----
public class SomeEvent
    extends Event
    implements SelfHandler {
    // implementation
}
----

=== Static methods

[source,java]
----
@Handler
public class SomeHandler {

    @Handles
    public static void handler(SomeEvent e, Bus bus) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public static void onException(SomeEvent e, Throwable ex, Bus bus) {}
}
----

=== Bean

[source,java]
----
@Handler
public class SomeHandler {

    private final Bus bus;

    public SomeHandler(Bus bus) {
        this.bus = bus;
    }

    @Handles
    public void handler(SomeEvent e) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public void onException(SomeEvent e, Throwable ex) {}
}
----


