= Echo Framework
:toc:

Simple event-based framework for developing high concurrent applications wth event-based domain model.

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-core</artifactId>
    <version>0.6.0</version>
</dependency>
----

You may want to use this library in Spring application.
If true you can add special dependency which will provide you annotation-based approach to register events and their handlers onto bus:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-spring</artifactId>
    <version>0.6.0</version>
</dependency>
----

For Quarkus integration you need the following:

[source,xml]
----
<dependency>
    <groupId>io.github.imashtak</groupId>
    <artifactId>echo-quarkus</artifactId>
    <version>0.6.0</version>
</dependency>
----

For more information of such integrations read <<Usage with Spring>> or <<Usage with Quarkus>>.

== Usage

=== Events

There are two main concepts: `Event` and `Bus`. You can publish event on bus and then subscribe to the type of that event to somehow handle it. It is not required to handle every event on the bus.

Let's start with simple event named `SignInInitiated`:

[source,java]
----
@Getter
public class SignInInitiated extends Event {
    private final String username;
    private final String password;

    public SignInInitiated(String username, String password) {
        super();
        this.username = username;
        this.password = password;
    }
}
----

Then we may create the bus and add to it handling method which will raises when event of type `SignInInitiated` will bbe published onto bus:

[source,java]
----
public class Main {
    public static void main(String[] args){
        // Bus instance required
        var bus = new Bus();

        // Adding handling method and exception resolver
        bus.subscribeOn(SignInInitiated.class,
            e -> {
                System.out.println("User '%s' signing in...".formatted(e.getUsername()));
            },
            (e, ex) -> {
                System.out.println("Something go wrong!");
            }
        );

        // Publishing event onto bus
        bus.publish(new SignInInitiated("user", "passwd"));
    }
}
----

Method `Bus::subscribeOn` is non-blocking, all handles will be executed in different threads.

So `Event` is a portion of data which can be handled asynchronously.

Each event carries a `Flow` -- special amount of data purposed to hold information about chain of events -- for tracing or debug stuff.

=== Tasks

What if we need to so some synchronous thing? For example, not just to react on users sign in, but also validate password, generate and return session token? Here comes `Task`, `Result`, `Succcess` and `Failure` classes.

Firstly we will change source code of `SignInInitiated` to the following:

[source,java]
----
@Getter
public class SignInInitiated extends Task<Failed, Succeed> {
    private final String username;
    private final String password;

    public SignInInitiated(String username, String password) {
        super();
        this.username = username;
        this.password = password;
    }

    @Getter
    public static class Succeed extends Success {
        private final String token;

        public Succeed(Task<?, ?> task, String token) {
            super(task);
            this.token = token;
        }
    }

    public static class Failed extends Failure {
        public Failed(Task<?, ?> task, Throwable cause) {
            super(task, cause);
        }
    }
}
----

After that we are becoming to have an ability to await result of task -- success or failure. Bus-connected code is following:

[source,java]
----
public class Main {
    public static void main(String[] args){
        // Bus instance required
        var bus = new Bus();

        // Adding handling method and exception resolver
        bus.subscribeOn(SignInInitiated.class,
            e -> {
                System.out.println("User '%s' signing in...".formatted(e.getUsername()));
                bus.publish(new SignInInitiated.Succeed(e, "token"));
            },
            (e, ex) -> {
                System.out.println("Something go wrong!");
                bus.publish(new SignInInitiated.Failed(e, ex));
            }
        );

        // Publishing task onto bus
        var task = new SignInInitiated("user", "passwd");
        bus.publish(task);
        // Awaiting result
        Mono<Result> resultAsync = bus.await(task);

        // Dealing with result
        var result = resultAsync.block();
        if (result.isSuccess()) {}
        else {}
    }
}
----

=== `SelfHandler` interface

Sometimes it is easier to be more "object-oriented" and place handling method near the data. `SelfHandler` interface provides that thing. Code is clear:

[source,java]
----
@Getter
public class SignInInitiated extends Event implements SelfHandler {
    private final String username;
    private final String password;

    public SignInInitiated(String username, String password) {
        super();
        this.username = username;
        this.password = password;
    }

    @Override
    public void handleSelf(Bus bus) {
        // any code
    }
}
----

After that patch the following code is enough to register handler onto bus:

[source,java]
----
bus.subscribeOn(SignInInitiated.class);
----

== Usage with Spring

Requires JVM option `echo.packages.to.scan` (comma separated list of packages) to discover event locations. Example:
[source,bash]
----
java -Decho.packages.to.scan=com.example.one,com.example.two ...
----

Package `echo-spring` provides three annotations:

* `@Handler` -- marks that this class contains handlers of a number of events;
* `@Handles` -- marks that this method is handler of some event;
* `@HandlesExceptionsOf` -- marks that this method must be triggered if there will be any exception in `@Handles`-method. Scope of such handles consists of methods in `@Handler`-class.

Also, this package provides Spring-configuration class called `EchoSpringConfiguration` which must be included to Spring application context, for example, in the following way:

[source,java]
----
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(
            new Class[] {Application.class, EchoSpringConfiguration.class},
            args
        );
    }
}
----

After that you will have bean of type `Bus` in the application context with automatically registered event handlers based on mentioned annotations.

There a number of ways how to declare handlers for auto registration.

=== `SelfHandler` interface

All events which implement interface `SelfHandler` will be auto registered.

[source,java]
----
public class SomeEvent
    extends Event
    implements SelfHandler {
    // implementation
}
----

=== Static methods

[source,java]
----
@Handler
public class SomeHandler {

    @Handles
    public static void handler(SomeEvent e, Bus bus) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public static void onException(SomeEvent e, Throwable ex, Bus bus) {}
}
----

=== Bean

[source,java]
----
@Handler
public class SomeHandler {

    private final Bus bus;

    public SomeHandler(@Lazy Bus bus) {
        this.bus = bus;
    }

    @Handles
    public void handler(SomeEvent e) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public void onException(SomeEvent e, Throwable ex) {}
}
----

It is important to lazy wire `Bus` dependency.

=== Flow

All events have flow associated with them -- mostly for tracing reasons. Also flow can hold initiator id in its field `Flow::initiator`. You can use it in any way you want.

== Usage with Quarkus

Requires JVM option `echo.packages.to.scan` (comma separated list of packages) to discover event locations. Example:
[source,bash]
----
java -Decho.packages.to.scan=com.example.one,com.example.two ...
----

Package `echo-quarkus` provides three annotations:

* `@Handler` -- marks that this class contains handlers of a number of events;
* `@Handles` -- marks that this method is handler of some event;
* `@HandlesExceptionsOf` -- marks that this method must be triggered if there will be any exception in `@Handles`-method. Scope of such handles consists of methods in `@Handler`-class.

Also, this package provides Spring-configuration class called `EchoQuarkusConfiguration` which provides singleton instance of `Bus` to CDI. It automatically registers event handlers onto bus.

There a number of ways how to declare handlers for auto registration.

=== `SelfHandler` interface

All events which implement interface `SelfHandler` will be auto registered.

[source,java]
----
public class SomeEvent
    extends Event
    implements SelfHandler {
    // implementation
}
----

=== Static methods

[source,java]
----
@Handler
public class SomeHandler {

    @Handles
    public static void handler(SomeEvent e, Bus bus) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public static void onException(SomeEvent e, Throwable ex, Bus bus) {}
}
----

=== Bean

[source,java]
----
@Handler
public class SomeHandler {

    private final Bus bus;

    public SomeHandler(Bus bus) {
        this.bus = bus;
    }

    @Handles
    public void handler(SomeEvent e) {}

    @HandlesExceptionsOf({SomeEvent.class})
    public void onException(SomeEvent e, Throwable ex) {}
}
----


