# https://github.com/bitnami/bitnami-docker-kafka
version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      # port 2181

  kafka:
    image: "bitnami/kafka:2.8.1"
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1 # broker.id=
      KAFKA_CFG_LISTENERS: INSIDE://:9092,OUTSIDE://:29092 # listeners=
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092 # advertised.listeners=
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181 # zookeeper.connect=
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32m -Xmx64m"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
