name: cd
run-name: Echo CD
on: [workflow_dispatch]
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Maven settings
        run: echo "$MAVEN_SETTINGS_XML" > settings.xml
        shell: bash
        env:
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Deploy Core
        run: cd echo-core && mvn -q --settings=../settings.xml -DskipTests clean package verify deploy && cd ..
      - name: Maven Deploy Spring
        run: cd echo-spring && mvn -q --settings=../settings.xml -DskipTests clean package verify deploy && cd ..
