name: deploy-to-maven-central
run-name: Deploy to Maven Central
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Maven Settings
        run: echo ${{ secrets.MAVEN_SETTINGS_XML }} > settings.xml
      - name: Maven Deploy
        run: cd echo-core && mvn --settings=../settings.xml clean deploy
